[package]
name = "vm-proto"
version = "0.1.0"
edition = "2018"

[dependencies]
bytecheck = "0.6.5"
rkyv = { version = "0.7.9", features = ["validation"] }
thiserror = "1.0.26"
wasmer = { version = "2.0.0", optional = true }

[dev-dependencies]
plutocracy = { path = "contracts/plutocracy" }

[features]
default = ["host"]
host = ["wasmer"]
